site_name: Siddhi-Execution-TensorFlow
extra_css:
- stylesheets/extra.css
extra_javascript:
- javascripts/extra.js
site_favicon: images/favicon.ico
extra:
  logo: images/siddhi-logo-w.svg
  palette:
    primary: teal
    accent: teal
google_analytics:
- UA-103065-28
- auto
pages:
- Welcome to WSO2 Siddhi Execution TensorFlow: index.md
- API Docs:
  - 1.0.0: api/1.0.0.md
  - latest: api/latest.md
- License: LICENSE.md
theme: material
